In [1]:
import numpy as np

a1=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<module 'numpy' from 'E:\\program\\anaconda\\lib\\site-packages\\numpy\\__init__.py'>
